openapi: 3.0.0
info:
  title: Valorant Stats API
  version: 1.0.0
  description: API for retrieving Valorant stats and sending messages to Discord.
servers:
  - url: http://localhost:5000
    description: Local server

paths:
  /:
    get:
      summary: Home page
      description: Returns a link to contact the developer on Discord.
      responses:
        '200':
          description: Successful response
          content:
            text/html:
              schema:
                type: string

  /health:
    get:
      summary: Health check
      description: Returns a health status message.
      responses:
        '200':
          description: Successful response
          content:
            text/plain:
              schema:
                type: string

  /rank/{region}/{id}/{tag}:
    get:
      summary: Get player rank
      description: Retrieves the current rank of a Valorant player.
      parameters:
        - in: path
          name: region
          required: true
          schema:
            type: string
          description: Player's region
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: Player's ID
        - in: path
          name: tag
          required: true
          schema:
            type: string
          description: Player's tag
      responses:
        '200':
          description: Successful response
          content:
            text/plain:
              schema:
                type: string
        '429':
          description: Too many requests
          content:
            text/plain:
              schema:
                type: string
        '400':
          description: Bad request
          content:
            text/plain:
              schema:
                type: string

  /lm/{query}:
    get:
      summary: Get last match stats
      description: Retrieves stats for the last match of a Valorant player.
      parameters:
        - in: path
          name: query
          required: false
          schema:
            type: string
          description: Player's ID and tag
      responses:
        '200':
          description: Successful response
          content:
            text/plain:
              schema:
                type: string
        '400':
          description: Bad request
          content:
            text/plain:
              schema:
                type: string

  /recb:
    get:
      summary: Get rank backup
      description: Retrieves rank changes for the current stream.
      responses:
        '200':
          description: Successful response
          content:
            text/plain:
              schema:
                type: string
        '400':
          description: Bad request
          content:
            text/plain:
              schema:
                type: string

  /rec:
    get:
      summary: Get match record
      description: Retrieves match records since the start of the current stream.
      responses:
        '200':
          description: Successful response
          content:
            text/plain:
              schema:
                type: string
        '400':
          description: Bad request
          content:
            text/plain:
              schema:
                type: string